//
// Created by Faulkes on 27/08/2019.
// C30 code
//

#ifndef L04_C_30_COMMS_STATE_MACHINE_DUMMYLIBS_H
#define L04_C_30_COMMS_STATE_MACHINE_DUMMYLIBS_H

/// THIS IS A PLACEHOLDER, REPLACE WITH THE REAL LIBRARY WHEN WE HAVE IT.
class ButtonLibDummy{

};


/// THIS IS A PLACEHOLDER, REPLACE WITH THE REAL LIBRARY WHEN WE HAVE IT.
class ControlLibDummy{

};



#endif //L04_C_30_COMMS_STATE_MACHINE_DUMMYLIBS_H
